unique_ids:
  forms:
    AddDesequilibrios: 6BZMVGHHRKOCCMHO222FZQOIN7KWJKJE
    Add_Desequilibrio: KFP6EL23AR4FHAYQCBLPS5KKBA2CKM5S
    ArticleView: CJXHCOBGI24OCKCVIH2R5IGHEWBSDFET
    HomeForm: '1677350116571428905718608.5461'
  modules: {}
  server_modules:
    ServerModule1: JY73GVS3P6CSBSLFQE6QNI6J7PPTLFVI
  assets:
    logo.png: '1677341902420704730476517.4894'
    standard-page.html: 6MNPRYZ5PDMYT2VOYOVLS4QVNWVKGZ6D
    theme.css: YJLPR76NRB55JMFYOSIIBZCSFBFGL2QJ
