unique_ids:
  forms:
    Add_Desequilibrio: KFP6EL23AR4FHAYQCBLPS5KKBA2CKM5S
    ArticleView: CJXHCOBGI24OCKCVIH2R5IGHEWBSDFET
    Homepage: 6BZMVGHHRKOCCMHO222FZQOIN7KWJKJE
  modules: {}
  server_modules:
    ServerModule1: JY73GVS3P6CSBSLFQE6QNI6J7PPTLFVI
  assets:
    standard-page.html: 6MNPRYZ5PDMYT2VOYOVLS4QVNWVKGZ6D
    theme.css: YJLPR76NRB55JMFYOSIIBZCSFBFGL2QJ
